# Generated by Django 4.0.1 on 2022-02-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_movie_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cinema',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cinema',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
